---
ID: "18a68a88-f1b0-4fa1-9c93-6182b366616b"
Parent: "57581ca8-d857-4527-998b-c6c6332747dd"
Template: "3b4fde65-16a8-491d-bf15-99ce83cf3506"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Channel/Online/Automation programs/SMS automation
DB: master
SharedFields:
- ID: "8fb875eb-3ad3-44ff-87e1-998370cc3199"
  Hint: Code
  Value: 10
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: da
  Fields:
  - ID: "8bdee96a-e8f5-446a-a1d2-568c3018c98e"
    Hint: Image
    Value: |
      <image mediaid="{903E4C67-D2D2-4BF4-B231-CB63D792EA34}" />
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Sms-automatisering"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104325Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Fields:
  - ID: "8bdee96a-e8f5-446a-a1d2-568c3018c98e"
    Hint: Image
    Value: |
      <image mediaid="{903E4C67-D2D2-4BF4-B231-CB63D792EA34}" />
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: SMS Automation
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104759Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Fields:
  - ID: "8bdee96a-e8f5-446a-a1d2-568c3018c98e"
    Hint: Image
    Value: |
      <image mediaid="{903E4C67-D2D2-4BF4-B231-CB63D792EA34}" />
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141115T110552Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "8bdee96a-e8f5-446a-a1d2-568c3018c98e"
    Hint: Image
    Value: |
      <image mediaid="{903E4C67-D2D2-4BF4-B231-CB63D792EA34}" />
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: SMS オートメーション
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105203Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
