---
ID: "ab6bb388-c390-42d7-a31f-42c1e70d8cd1"
Parent: "9f63f3ed-bfb8-49a3-b370-1830e0a5920f"
Template: "9f63f3ed-bfb8-49a3-b370-1830e0a5920f"
Path: /sitecore/templates/System/Item Buckets/Dropdown List/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "5e34a660-3099-4e49-87df-80eb1decf2a6"
  Hint: Enabled
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111103T143300
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d9bdf564-ff37-4564-b943-00d4d89c19f1"
      Hint: List Name
      Value: $name
