---
ID: "62495b9a-5bbb-43ec-99a1-3bf08c8f5ac9"
Parent: "448c4d57-f0f1-4278-8ab8-93db46c94f1b"
Template: "448c4d57-f0f1-4278-8ab8-93db46c94f1b"
Path: "/sitecore/templates/System/Analytics/Profile Card - Persona/__Standard Values"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110104T140234
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
