---
ID: "e1779438-9be6-4fce-93cf-5bafc930176e"
Parent: "d1592226-3898-4ce2-b190-090fd5f84a4c"
Template: "d1592226-3898-4ce2-b190-090fd5f84a4c"
Path: /sitecore/templates/System/Layout/Sections/Rendering Options/__Standard Values
DB: master
SharedFields:
- ID: "308e88f5-cd6e-4f8f-bafe-95a47dedefdc"
  Hint: Editable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110114T190400
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
