---
ID: "b831ebea-892f-412b-afd4-83b0eb4f9f76"
Parent: "9719ab0f-7300-41c0-8197-0fb2b9ca1c60"
Template: "9719ab0f-7300-41c0-8197-0fb2b9ca1c60"
Path: /sitecore/templates/System/Social/Connector/Base Login Button Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140910T103051Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
