---
ID: "141d11a7-df4c-4cac-80c3-9753c28ceb84"
Parent: "98ec37bf-bca6-40c6-a772-5c52190ef205"
Template: "98ec37bf-bca6-40c6-a772-5c52190ef205"
Path: /sitecore/templates/System/Item Buckets/Saved Search/__Standard Values
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 1
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{59F53BBB-D1F5-4E38-8EBA-0D73109BB59B}"
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\Everyone|pe|-item:read|au|$currentuser|pe|+item:read|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120912T070100
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
