---
ID: "cafdcd9e-b143-4bba-b4ba-8c04e3e3f709"
Parent: "850c2bd1-8d6a-4d6c-b77a-49fb5267cc39"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: /sitecore/system/Settings/Rules/Custom Search/Tags/Default
DB: master
BranchID: "bdc41fdd-a3ac-4b69-a0ba-471c425cb083"
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{7E2EEB28-8506-4D1D-8D28-A0719B6451D6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170117T200636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
