---
ID: "22554eeb-6022-4cea-a963-23d344527037"
Parent: "7941d7d1-24ae-4478-beab-0227e14a1cf9"
Template: "00a60c7a-2373-4e30-8197-920b8374509e"
Path: /sitecore/system/Modules/Experience Explorer/Components/ExpViewer/Page Configuration
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Sidekonfiguration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104326Z
    - ID: "4882658b-7490-4f7a-a16f-080bb4ae9e99"
      Hint: Accordion Name
      Value: Sidekonfiguration
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Seitenkonfiguration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104801Z
    - ID: "4882658b-7490-4f7a-a16f-080bb4ae9e99"
      Hint: Accordion Name
      Value: Seitenkonfiguration
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130401T224310
    - ID: "4882658b-7490-4f7a-a16f-080bb4ae9e99"
      Hint: Accordion Name
      Value: Page Configuration
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: ページ設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105205Z
    - ID: "4882658b-7490-4f7a-a16f-080bb4ae9e99"
      Hint: Accordion Name
      Value: ページ設定
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
