---
ID: "610dab8e-ec1e-4ca2-8d62-e9aaa9952171"
Parent: "5ad1d932-f10e-40af-8b48-4adb24e81871"
Template: "f0d16eee-3a05-4e43-a082-795a32b873c0"
Path: /sitecore/system/Settings/Rules/Definitions/Obsolete/Marketing Workflows/Conditions/Automation State/Has Automation
DB: master
SharedFields:
- ID: "ab51c8b2-f0e1-4471-9aae-cc080d774923"
  Hint: Type
  Value: Sitecore.Analytics.Automation.Rules.Workflows.Conditions.HasAutomationCondition,Sitecore.Analytics.Automation
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Har automatisering
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104335Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "hvor den aktuelle besøgende er i enhver fase af [automationid,Tree,root={4497A9BE-0A00-4EE4-9AE0-50D6CBB4FAB2},specific] engagementsplan"
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Hat Automation
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104811Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "wo der aktuelle Besucher sich in einem Status des [automationid,Tree,root={4497A9BE-0A00-4EE4-9AE0-50D6CBB4FAB2},spezifischen] Engagement Plans befindet"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090202T181635
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "where the current visitor is in any state of the [automationid,Tree,root={4497A9BE-0A00-4EE4-9AE0-50D6CBB4FAB2},specific] engagement plan"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: オートメーションが設定されている
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105216Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "条件： （エンゲージメント） 現在のビジターが [automationid,Tree,root={4497A9BE-0A00-4EE4-9AE0-50D6CBB4FAB2},特定の] エンゲージメント プランのいずれかの状態にいる場合"
