---
ID: "91be1033-4910-44ee-81a1-adafd070dc2b"
Parent: "1b875849-05b5-4cae-97e0-53c3ace54183"
Template: "1b875849-05b5-4cae-97e0-53c3ace54183"
Path: /sitecore/templates/System/Content Testing/Test Type/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140307T115108
    - ID: "5ad56443-878e-4fa6-b3d3-0e527294f634"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
