---
ID: "4e76168a-b56b-4590-b4f8-c4023c9c3d02"
Parent: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/templates/System/Analytics/Marketing Taxonomy/Custom/Custom Taxon/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141031T092654Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
