---
ID: "2bb14df3-2e29-4a7e-8398-6bf5193485af"
Parent: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Template: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Path: /sitecore/templates/System/Analytics/Marketing Taxonomy/Campaign group/Campaign group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141029T210315Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
