---
ID: "5c2445e9-51a7-41f7-a68d-83480af34938"
Parent: "249a9c7d-bad8-451f-8d95-cc1a393b40f5"
Template: "249a9c7d-bad8-451f-8d95-cc1a393b40f5"
Path: /sitecore/templates/System/Layout/Preview Simulators/Trait/__Standard Values
DB: master
SharedFields:
- ID: "fe5c1799-fa2a-4a5a-9c2b-d67bc1668d28"
  Hint: Type
  Value: Sitecore.Pipelines.ProcessSimulatorResponse.ProcessHtml, Sitecore.Kernel
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110720T153400
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
