---
ID: "482c3a4c-b1df-4816-9c04-1711af2f58d2"
Parent: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/templates/System/Media/Unversioned/Image/__Standard Values
DB: master
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20121130T051800
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
