---
ID: "a454280a-41dd-4648-b7ce-01dba1b6b920"
Parent: "271f5cf1-95c7-474d-9f04-06c6ebb20d8f"
Template: "271f5cf1-95c7-474d-9f04-06c6ebb20d8f"
Path: /sitecore/templates/System/Rules/Taxonomy/Rule Elements Visibility Rule/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120807T153200
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: $name
