---
ID: "c384c542-cd15-4612-9ab9-b6dd54f2aa1e"
Parent: "40620822-190c-47b9-b8b6-052b9a8de072"
Template: "40620822-190c-47b9-b8b6-052b9a8de072"
Path: /sitecore/templates/System/Social/Connector/Login with Twitter Button Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140327T103558
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
