---
ID: "fae11f30-e791-4348-bff6-fd2ab3ffd027"
Parent: "314be5b0-8536-45cf-900d-a84b2b335210"
Template: "314be5b0-8536-45cf-900d-a84b2b335210"
Path: /sitecore/templates/System/Content Testing/Multivariate Test Strategy/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20081210T113423
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
