---
ID: "716a19ca-b20a-40ba-a85b-c48184730ec8"
Parent: "26615351-70c2-4743-90e0-43671862db9c"
Template: "26615351-70c2-4743-90e0-43671862db9c"
Path: /sitecore/templates/System/Analytics/Federated Experience Manager/Filters and Actions/Client Action/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140227T150143
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
