---
ID: "012c516f-f81f-4f00-9234-29fcd7159621"
Parent: "82969ff1-15fa-4cdc-8ca4-5204a6add761"
Template: "82969ff1-15fa-4cdc-8ca4-5204a6add761"
Path: /sitecore/templates/System/Experience Analytics/Dimension/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140613T153326
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
