---
ID: "935fc736-d86f-47bb-9fe1-e7430f046a00"
Parent: "ee43c2f0-6277-4144-b144-8ca2cefccf12"
Template: "ee43c2f0-6277-4144-b144-8ca2cefccf12"
Path: /sitecore/templates/System/Analytics/Outcome/Outcome Definition/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{689E2994-4656-4C58-9112-7826CB46EE69}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140704T133402Z
    - ID: "2a8d9ab0-b1c1-4da3-b17d-1610ad23d697"
      Hint: Name
      Value: $name
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
