---
ID: "7d2c010b-5456-4ac4-bf08-52aa86511bd7"
Parent: "e360bed5-b72b-4c02-890f-e434486de3f1"
Template: "e360bed5-b72b-4c02-890f-e434486de3f1"
Path: /sitecore/templates/System/Experience Explorer/Control/__Standard Values
DB: master
SharedFields:
- ID: "ad8d5f6d-d0a3-4f86-a4e7-c29ff7427597"
  Hint: Path
  Value: /sitecore modules/Web/ExperienceExplorer/Controls/...
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130401T204132
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "804e29ad-9cff-4d31-b4d4-b5a6daed990b"
      Hint: Tab Name
      Value: $name
