---
ID: "a7b53fd2-c19b-43f7-a42c-7a67fd69a37e"
Parent: "cd35e9cc-8a38-4f29-ba95-dc1c89a4b48f"
Template: "cd35e9cc-8a38-4f29-ba95-dc1c89a4b48f"
Path: /sitecore/templates/System/Path Analyzer/ChannelMap/__Standard Values
DB: master
SharedFields:
- ID: "a87e94ef-d136-4fed-b69f-d69caac3ec8d"
  Hint: MapItemType
  Value: Sitecore.PathAnalyzer.Data.Maps.ChannelMapItem,Sitecore.PathAnalyzer
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104346Z
    - ID: "31fcbeb2-376a-481f-bb44-ef52301f33ca"
      Hint: Description
      Value: |
        <p>Denne oversigt viser den besøgendes oplevelse af kanalen "$name".</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104822Z
    - ID: "31fcbeb2-376a-481f-bb44-ef52301f33ca"
      Hint: Description
      Value: |
        <p>Diese Karte zeigt Besuchererfahrungen des Kanals "$Name".</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140611T212731Z
    - ID: "31fcbeb2-376a-481f-bb44-ef52301f33ca"
      Hint: Description
      Value: |
        <p>This map shows visitor experience of the "$name" channel.</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a44d8693-f962-4f76-8fb8-62525ce67ba1"
      Hint: Name
      Value: $name
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105228Z
    - ID: "31fcbeb2-376a-481f-bb44-ef52301f33ca"
      Hint: Description
      Value: |
        <p>このマップは "$name" チャネルの訪問者エクスペリエンスを表示します</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
