---
ID: "652e2a54-9965-4304-8d8d-1d1e9874d43d"
Parent: "cebf2ea3-e6ee-4564-9d76-f71f431f6af6"
Template: "cebf2ea3-e6ee-4564-9d76-f71f431f6af6"
Path: /sitecore/templates/System/Services/Item Service/Query/Query Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {79E0E28F-5591-410E-A086-754EDC7CEF88}
    {CEBF2EA3-E6EE-4564-9D76-F71F431F6AF6}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140226T121838
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
