---
ID: "cc5d7fe5-8fab-4041-b238-e78e05429d24"
Parent: "3baa73e5-6ba9-4462-bf72-c106f8801b11"
Template: "3baa73e5-6ba9-4462-bf72-c106f8801b11"
Path: /sitecore/templates/System/Layout/Renderings/Sublayout Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {BD3AD888-7E9B-407E-95AF-ADFE0FD1DDEB}
    {3BAA73E5-6BA9-4462-BF72-C106F8801B11}
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20081124T123347
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
