---
ID: "cbe7df8c-f4b1-4f7b-a816-8f3af6af7363"
Parent: "239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"
Template: "239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"
Path: /sitecore/templates/System/Node/__Standard Values
DB: master
SharedFields:
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20080311T143005
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
