---
ID: "aa555584-8cbc-46da-a67e-0d606e4d2567"
Parent: "a6575aec-8bc5-4591-b730-8fcdc0ccddb5"
Template: "a6575aec-8bc5-4591-b730-8fcdc0ccddb5"
Path: /sitecore/templates/System/Social/Posting Configuration/Content Posting Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111114T144259
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
