---
ID: "062f23e0-ea6a-4ff6-a403-d2b0a0d1d680"
Parent: "01471d8b-8681-4a6d-9881-bfabfa7ca7c7"
Template: "01471d8b-8681-4a6d-9881-bfabfa7ca7c7"
Path: /sitecore/templates/System/Social/Posting Configuration/Container Posting Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130725T154700
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
