---
ID: "b4ae16a9-ea2f-4d5b-905e-7299975316a2"
Parent: "403f5fe8-9bc4-4ff5-a092-e98e44f565af"
Template: "403f5fe8-9bc4-4ff5-a092-e98e44f565af"
Path: /sitecore/templates/System/Validation/Rules Validation Rule/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20100307T110855
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
