---
ID: "f8aae0ec-76d0-4147-bb9f-d8301b612d96"
Parent: "e43cb7ec-44a5-4a92-9eb6-f1ca7a385c5d"
Template: "e43cb7ec-44a5-4a92-9eb6-f1ca7a385c5d"
Path: /sitecore/templates/System/Content Testing/Workflow/Remove Tests Action/__Standard Values
DB: master
SharedFields:
- ID: "a291a22b-99e2-46bb-a27b-8ec744275396"
  Hint: Type
  Value: Sitecore.ContentTesting.Workflows.RemoveTestsAction, Sitecore.ContentTesting
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141107T014924Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
