---
ID: "536bb534-7f7e-409c-b491-e147fcf6bc97"
Parent: "07b3e5f1-7f8e-49ad-b484-25a0d45745e7"
Template: "271f5cf1-95c7-474d-9f04-06c6ebb20d8f"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/GeoIP/Visibility/Default
DB: master
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Synlighed for GeoIP
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104333Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "664ceceb-0446-4063-92a3-1e14837f4d0c"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{E8E788A7-195C-46A5-96EF-CB10F7C66BB1}">
            <conditions>
              <condition
                id="{419CF8CE-EDC4-4D24-B7C4-4730DB9E9CDE}"
                uid="4B81E1E304B642D6841C806B8D367583"
                except="true" />
            </conditions>
            <actions>
              <action
                id="{EDDE9129-8CF8-4630-A625-56BA8E38489E}"
                uid="48B4910E821A4253A530AEFF77F41F43" />
            </actions>
          </rule>
        </ruleset>
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: Synlighed for GeoIP
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: GeoIP Sichtbarkeit
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104809Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "664ceceb-0446-4063-92a3-1e14837f4d0c"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{E8E788A7-195C-46A5-96EF-CB10F7C66BB1}">
            <conditions>
              <condition
                id="{419CF8CE-EDC4-4D24-B7C4-4730DB9E9CDE}"
                uid="4B81E1E304B642D6841C806B8D367583"
                except="true" />
            </conditions>
            <actions>
              <action
                id="{EDDE9129-8CF8-4630-A625-56BA8E38489E}"
                uid="48B4910E821A4253A530AEFF77F41F43" />
            </actions>
          </rule>
        </ruleset>
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: GeoIP Sichtbarkeit
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120807T152400
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "664ceceb-0446-4063-92a3-1e14837f4d0c"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{E8E788A7-195C-46A5-96EF-CB10F7C66BB1}">
            <conditions>
              <condition
                id="{511843B5-62DE-46AB-86C5-002F017D053C}"
                uid="307D2E6F4B8041BBA5E3F8B2DA2903F3"
                except="true" />
            </conditions>
            <actions>
              <action
                id="{EDDE9129-8CF8-4630-A625-56BA8E38489E}"
                uid="48B4910E821A4253A530AEFF77F41F43" />
            </actions>
          </rule>
        </ruleset>
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: GeoIP visibility
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: GeoIP 表示/非表示
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105214Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "664ceceb-0446-4063-92a3-1e14837f4d0c"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{E8E788A7-195C-46A5-96EF-CB10F7C66BB1}">
            <conditions>
              <condition
                id="{419CF8CE-EDC4-4D24-B7C4-4730DB9E9CDE}"
                uid="4B81E1E304B642D6841C806B8D367583"
                except="true" />
            </conditions>
            <actions>
              <action
                id="{EDDE9129-8CF8-4630-A625-56BA8E38489E}"
                uid="48B4910E821A4253A530AEFF77F41F43" />
            </actions>
          </rule>
        </ruleset>
    - ID: "f9abbe04-6a99-49da-906d-8b0a709c377f"
      Hint: Name
      Value: GeoIP 表示/非表示
