---
ID: "b85ed1b3-037c-47a0-8bac-f5908b9291af"
Parent: "bab68954-d9e6-464d-88e5-c207cb392aa7"
Template: "bab68954-d9e6-464d-88e5-c207cb392aa7"
Path: /sitecore/templates/System/Experience Explorer/Preset Persona/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110104T140234
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
