---
ID: "7fd10146-77c7-4a20-bda5-103d77ab73ca"
Parent: "d9bdf22f-6e17-47f3-ab64-49c717ba92da"
Template: "d9bdf22f-6e17-47f3-ab64-49c717ba92da"
Path: /sitecore/templates/System/Rules/Rule/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090818T190507
    - ID: "45cf9130-802a-41be-b3eb-c02f657dcc2e"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
